FROM debian:oldstable

RUN apt update -y
RUN apt upgrade -y
RUN apt install php-fpm php-mysql -y && apt install curl -y

COPY ./tools/auto-config.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/auto-config.sh
ENTRYPOINT ["/usr/local/bin/auto-config.sh"]

EXPOSE 9000
